##Playbook który deployuje aplikacje do dockera tomcat##
- hosts: node2
  become: yes
  tasks:
    - name: Pobieranie z gita aplikacji
      git:
        repo: https://github.com/Mikzzer/Tomcat_deploy.git
        dest: /home/vagrant/repo
    - name: Kopiowanie aplikacji do dockerfile
      copy:
        remote_src: yes
        src: /home/vagrant/repo/war/SampleWebApp.war
        dest: /home/vagrant/Docker/
    - name: Instalacja modułu Pythona dla Docker SDK
      apt:
        name: python3-pip
        state: present
    - name: Moduł do dockera
      become: yes
      pip:
        name: docker
        state: present 
    - name: Pobranie obrazu
      docker_image:
        name: tomcat:latest
    - name: Odpalenie dockera z obrazem
      docker_container:
        name: tomcat-container
        image: tomcat:latest
        ports:
          - "8090:8080"
        volumes:
          - "/home/vagrant/Docker/SampleWebApp.war:/usr/local/tomcat/webapps/SampleWebApp.war"
        restart_policy: always
